on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Generate Html und Publish

jobs:
  deploy-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
         node-version: 18
      - name: Prepare repo
        run: |
          git fetch origin
          git config --global user.email "mechtel@iqb.hu-berlin.de"
          git config --global user.name "Martin Mechtel"
          git checkout gh-pages
          git merge -X theirs main --allow-unrelated-histories
      - name: Run html generation
        run: |
          npm ci
          npm run generate
          mv docs/index.html index.html
      - name: Push changes
        run: |
          echo pre-add-status---------------
          git status
          git add index.html
          echo post-add-status--------------
          git status
          git commit -m "update gh-pages"
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
