on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Generate Html und Publish

jobs:
  deploy-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
     - uses: actions/setup-node@v4
       with:
         node-version: 18
     - run: |
          npm install
          npm run validate
     - name: Archive production artifacts
       uses: actions/upload-artifact@v4
       with:
         name: docs
         path: docs
         overwrite: true
         target: gh-pages
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
